# This file enables the Travis continuous integration system, which
# automatically builds and tests the project for each GitHub commit or
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

sudo: true

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.12

before_install:
  - export PATH=${PATH}:./vendor/bundle

env:
  - TRAVIS_NODE_VERSION="9.2.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - rvm use 2.3.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.6.2

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.coursier
    - $HOME/.sbt/boot

script:
  - sbt "++${TRAVIS_SCALA_VERSION}! -v" -J-Xmx4G clean scalajavatimeTestsJVM/test "show scalajavatimeTestsNative/nativeMissingDependencies" scalajavatimeTestsJS/test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
